### ISSUE TITLE
Add more detail to Client Authentication section.

### ISSUE THREAD

**Issue by ajmcmiddlin** [ConsumerDataStandardsAustralia/infosec#19]
The [Client Authentication](https://consumerdatastandardsaustralia.github.io/infosec/#introspection-endpoint) section mentions the "Directory Issuer metadata", but it's not clear to me what this is. A hyperlink or description would be helpful.

Furthermore, I think it would be helpful to be explicit about when client authentication is used and how it differs to MTLS as a holder of key mechanism.

**Comment by lukepopp** [comment]
I believed this is now fixed.
