### ISSUE TITLE
`acr_values` not compatible with FAPI?

### ISSUE THREAD

**Issue by ajmcmiddlin** [ConsumerDataStandardsAustralia/infosec#20]
My understanding from [FAPI Part 2 &#167;5.2.3](https://openid.net/specs/openid-financial-api-part-2.html#public-client) is that the authorisation request _must_ make an `acr` claim as an **essential** claim. [OIDC &#167;5.5.1.1](https://openid.net/specs/openid-connect-core-1_0.html#acrSemantics) and [OIDC &#167;3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) both suggest that `acr_values`, which is currently optional in this spec, is a voluntary claim.

It seems to me that to comply with FAPI we must include an `acr` claim as part of the ID Token claims in the request object as per [OIDC &#167;5.5](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) (noting sections 5.5.1 and 5.5.1.1).

Furthermore, including both `acr_values` and an `acr` claim as part of the ID token claims is unspecified according to OIDC &#167;5.5.1.1.

Taken together, this suggests to me that if we want to comply with FAPI (I don't see a good reason not to) we should remove the `acr_values` parameter and instead require the `acr` claim be made within the ID token claims.

**Comment by lukepopp** [comment]
That's true for write operations.  From my understand read ops do not have such a requirement https://openid.net/specs/openid-financial-api-part-1.html 5.2.2.1
However, I think this a good example of why the profile needs to make it clear what's normative and not be overly prescriptive.
