### ISSUE TITLE
Authorisation endpoint should use MTLS.

### ISSUE THREAD

**Issue by ajmcmiddlin** [ConsumerDataStandardsAustralia/infosec#31]
[&#167;13.2](https://consumerdatastandardsaustralia.github.io/infosec/#13-2-authorisation-endpoint) of version `0.0.3` of this spec says the authorisation endpoint uses TLS. I believe it should use MTLS.

[FAPI part 2 &#167;5.2.2](https://openid.net/specs/openid-financial-api-part-2.html#authorization-server) includes the following.

> 5. shall only issue authorization code, access token, and refresh token that are holder of key bound;
> 6. shall support [OAUTB] or [MTLS] as a holder of key mechanism; 

[&#167;11.3](https://consumerdatastandardsaustralia.github.io/infosec/#11-3-holder-of-key-mechanism) of version `0.0.3` of this spec forbids using OAUTB and therefore only allows MTLS to be used. As a result, for the authorization code to be holder of key bound I believe the authorisation endpoint must use MTLS.

**Comment by ajmcmiddlin** [comment]
I agree. Now that I think about it MTLS is impractical as you say. How does FAPI part 2 expect authorization codes to be holder of key bound then? I feel like I'm misunderstanding what they're mandating, or it's an oversight in the spec.

**Comment by lukepopp** [comment]
Good question. You could enforce HOK where the Auth Code goes to say a device (implicit flow) which then calls the TokenEndpoint but can't see how it work with separate systems.

**Comment by TakahikoKawasaki** [comment]
FYI: I had the same interpretation as @ajmcmiddlin. See "[fapi issue 202](https://bitbucket.org/openid/fapi/issues/202)" if you are interested.
