### ISSUE TITLE
Changing consentId field as part of cliams in Request Object

### ISSUE THREAD

**Issue by krishna1c** [ConsumerDataStandardsAustralia/infosec#42]
In the current draft of infosec consentId field is part of request object but it is outside the claims. 
It is more appropriate to add consentId as part of claims, due to this OIDC providers can easily identity the cosentId.

**Comment by lukepopp** [comment]
Thanks.  You are correct.  It should be an essential claim.  Will fix.

**Comment by krishna1c** [comment]
Also add vot and vtr also as a claims.

**Comment by lukepopp** [comment]
They should be there already.

**Comment by krishna1c** [comment]
Ya. In the examples it is mentioned outside the claims.
Thanks
