### ISSUE TITLE
Sector Identifier URIs 

### ISSUE THREAD

**Issue by davidgtonge** [ConsumerDataStandardsAustralia/infosec#48]
I'm interested to understand why:
> Sector Identifier URIs  SHALL NOT be supported under this profile

If PPIDs are mandated then sector identifier uris are very useful.

For example OIDC says this:
> If there are multiple hostnames in the registered redirect_uris, the Client MUST register a sector_identifier_uri.

So by not allowing a sector identifier uri, you would be restricting Clients to a single hostname for any of their redirect uris.

**Comment by lukepopp** [comment]
@davidgtonge this is primarily an attempt to limit scope and will also be dependent on registration of a client which in turn is dependent on the CDR Registry/Directory.  Unless I've missed it, I don't see `sector_identifier_uri` as part of the OBIE Software Statement which is interesting.  There is no reason `sector_identifier_uri` couldn't be supported but this would need to reflect the 
CDR Registry entities and their relationships which is unspecified thus far.   Given the change in delivery date, scope may change to include this.
