### ISSUE TITLE
Is `cdr_consent_id` an essential claim in both `id_token` and `userinfo`?

### ISSUE THREAD

**Issue by ajmcmiddlin** [ConsumerDataStandardsAustralia/infosec#52]
&#167;12 of the specification contains an example in which `cdr_consent_id` is an essential claim in both the `id_token` and `userinfo` claims. Is this correct? It seems redundant as I would expect `cdr_consent_id` to only appear in the `id_token` claim.

**Comment by lukepopp** [comment]
Yeah it needs to be in both as they control what is in the UserInfo response versus what goes in the ID Token (from the Token Endpoint)
