### ISSUE TITLE
`redirect_uris` must be HTTPS and not localhost

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/infosec#54]
Should the specification of `redirect_uris` in `Client Registration Endpoint` include a mention of the mandatory requirement that redirect URIs need to be HTTPS and also not localhost URIs?

**Comment by lukepopp** [comment]
This should be present in the referenced profiles (FAPI or OIDC).

**Comment by JamesMBligh** [comment]
As this is in the normative profiles that are referenced this issue will be closed

-JB-
