### ISSUE TITLE
Consent APIs

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/infosec#58]
Is it [still expected](https://consumerdatastandardsaustralia.github.io/infosec/#14-consent) that details of the APIs for querying, communication and revocation of consents will be published? Will the approach be based on the [Account Access Consents APIs](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/937558092/Account+Access+Consents+v3.1) from the UK standard?

**Comment by JamesMBligh** [comment]
Yes, APIs will be published.  They are currently under development.  No ETA yet

**Comment by JamesMBligh** [comment]
This has been clarified in issue #47 with the following comment:
https://github.com/ConsumerDataStandardsAustralia/infosec/issues/47#issuecomment-479275972
