### ISSUE TITLE
Is there any standard error specifications for Token and Consent Setup API's?

### ISSUE THREAD

**Issue by krishna1c** [ConsumerDataStandardsAustralia/infosec#62]
Hi,

Is there any standard on error specifications for Token and Consent Setup API's?

Thanks
Vamsikrishna P.

**Comment by JamesMBligh** [comment]
The consent API will not be included in the standard for v1.  The behaviour of the token end point should align to the normative references that define its operation.  There is currently no expectation that the CDR profile will add to the normative references in this regard unless there is a clear need articulated.

-JB-
