### ISSUE TITLE
ES256 Support

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/infosec#66]
It has been suggested to me via a bilateral meeting that support for ES256 be removed due to perceived jurisdictional risks.  As support for PS256 is also included in the profile my understanding is that this would not harm the operation of the regime.

Would there be any concerns or risks with the removal of support for ES256?

**Comment by NationalAustraliaBank** [comment]
NAB is supportive of removing ES256 from the supported list of ciphers

**Comment by JamesMBligh** [comment]
This has been actioned.
