### ISSUE TITLE
Client Authentication - Private Key Support Only

### ISSUE THREAD

**Issue by lukepopp** [ConsumerDataStandardsAustralia/infosec#7]
At present, the profile supports Client Authentication via _private key JWT_ and _Mutual Authentication TLS (MTLS)_.  This means that Holders will need to support both methods.  It is proposed that only _private key JWT_ client authentication will be supported under the profile.
**This does not mean that MTLS as a Holder of Key Mechanism will no longer be required - it is required regardless of this proposal.  Furthermore, Server/client certs must be issued by the CDR CA.**

**Comment by NationalAustraliaBank** [comment]
NAB is supportive of the proposal - i.e to use private key JWT for client authentication.

**Comment by MacquarieBank** [comment]
Macquarie Bank also strongly endorses and supports the proposal that only private key JWT client authentication will be supported under the CDR InfoSec profile.

**Comment by lukepopp** [comment]
Commonwealth Bank's response:

> Commonwealth Bank supports the use of mutual TLS and private_key_JWT for client authentication and to enable the sending of certificate bound access tokens.

[20181219 CommBank Standards Submission.pdf](https://github.com/ConsumerDataStandardsAustralia/infosec/files/2730906/20181219.CommBank.Standards.Submission.pdf)

**Comment by lukepopp** [comment]
There is broad support for this proposal and this will be reflected in the InfoSec profile.
